name: Cache Node and NPM dependencies
description: This action caches Node and NPM dependencies based on the package-lock.json file

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.9'
  working-dir:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-dir }}/python_modules
        key: python-module-${{ hashFiles('${{ inputs.working-dir }}/requirements.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ${{ inputs.working-dir }}/requirements.txt
      shell: bash
      working-directory: ${{ inputs.working-dir }}

