name: 04- Using Actions
on: workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        # 0. Checkout the code
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: |
                    ls -la
        # 1. Install deps
        # 2. Execute automated tests 