name: 11 - Working With Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: 'Skip deployment and only print build ouput'
                default: false
            target:
                type: environment
                required: true
                description: 'Wich environment the workflow will target'
            tag:
                type: choice
                options: 
                    - v1
                    - v2
                default: v3
                description: 'Release from wich to build a deploy'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"