name: 12 - Working With Outputs
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                description: 'Status of the build'
                options:
                    - success
                    - failure
                    - cancelled
                default: 'success'
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
                build-status: ${{ steps.build.outputs.status }} 
                output1: ${{ steps.build.outputs.output1 }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT" 
            - name: Build
              id: build
              run: |
                echo "$GITHUB_OUTPUT"
                echo "status=${{ inputs.build-status}}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
                echo "mistake=true" > "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              if: ${{ needs.build.outputs.build-status == 'success' }}
              run: echo "Deploying with status ${{ needs.build.outputs.build-status }}"
            - name: Print Outputs
              run: |
                echo "Output1: ${{ needs.build.outputs.output1 }}"